# 📌 NumPy Complete Guide: Beginner to Advanced

NumPy (Numerical Python) is the core library for numerical computing in Python.  
It provides fast, efficient arrays and mathematical functions.

---

## 🔹 1. Import NumPy
```python

In [1]:
import numpy as np

### 🔹 2. Creating NumPy Arrays

In [2]:
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)

[1 2 3 4 5]


##### 2D Array

In [3]:
arr2 = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print(arr2)

[[1 2 3]
 [4 5 6]]


##### 3D Array

In [4]:
arr3 = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])
print(arr3)


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### 🔹 3. Array Properties

In [5]:
print(arr2.ndim)     # Number of dimensions
print(arr2.shape)   # Rows and columns
print(arr2.size)    # Total elements
print(arr2.dtype)   # Data type

2
(2, 3)
6
int64


### 🔹 4. Special Arrays

In [6]:
zeros = np.zeros((3, 3))
ones = np.ones((2, 4))
identity = np.eye(3)

print(zeros)
print(ones)
print(identity)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### 🔹 5. Range & Random Arrays

##### Range

In [7]:
arr_range = np.arange(1, 11, 2)
print(arr_range)

[1 3 5 7 9]


##### Linspace

In [8]:
lin = np.linspace(0, 10, 5)
print(lin)

[ 0.   2.5  5.   7.5 10. ]


##### Random Arrays

In [9]:
rand1 = np.random.rand(3, 3)
rand2 = np.random.randint(1, 100, (3, 3))

print(rand1)
print(rand2)

[[0.40935037 0.0844319  0.29662756]
 [0.1428428  0.45351897 0.9105354 ]
 [0.61631577 0.80090158 0.93911955]]
[[72 62 31]
 [77 54 81]
 [53 70 10]]


### 🔹 6. Array Indexing & Slicing

##### 1D Indexing

In [10]:
arr = np.array([10, 20, 30, 40, 50])

print(arr[0])
print(arr[-1])
print(arr[1:4])

10
50
[20 30 40]


##### 2D Indexing

In [11]:
mat = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(mat[0, 1])
print(mat[:, 1])
print(mat[1, :])

2
[2 5]
[4 5 6]


### 🔹 7. Reshaping Arrays

In [12]:
arr = np.arange(1, 13)
reshaped = arr.reshape(3, 4)
print(reshaped)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


##### Flatten

In [13]:
flat = reshaped.flatten()
print(flat)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


### 🔹 8. Mathematical Operations

In [14]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)
print(a - b)
print(a * b)
print(a / b)
print(a ** 2)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[1 4 9]


### 🔹 9. Universal Functions (ufuncs)

In [15]:
arr = np.array([1, 4, 9, 16])

print(np.sqrt(arr))
print(np.log(arr))
print(np.exp(arr))
print(np.sin(arr))

[1. 2. 3. 4.]
[0.         1.38629436 2.19722458 2.77258872]
[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06]
[ 0.84147098 -0.7568025   0.41211849 -0.28790332]


### 🔹 10. Aggregation Functions

In [16]:
data = np.array([10, 20, 30, 40, 50])

print(np.sum(data))
print(np.mean(data))
print(np.max(data))
print(np.min(data))
print(np.std(data))

150
30.0
50
10
14.142135623730951


### 🔹 11. Boolean Indexing

In [17]:
arr = np.array([10, 25, 30, 5, 40])

print(arr[arr > 20])
print(arr[arr % 2 == 0])

[25 30 40]
[10 30 40]


### 🔹 12. Copy vs View

In [18]:
arr = np.array([1, 2, 3, 4])

view_arr = arr.view()
copy_arr = arr.copy()

arr[0] = 100

print(arr)
print(view_arr)
print(copy_arr)

[100   2   3   4]
[100   2   3   4]
[1 2 3 4]


### 🔹 13. Stacking & Splitting Arrays

##### Stacking

In [19]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(np.hstack((a, b)))
print(np.vstack((a, b)))

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


##### Splitting

In [20]:
arr = np.array([1, 2, 3, 4, 5, 6])
print(np.split(arr, 3))

[array([1, 2]), array([3, 4]), array([5, 6])]


### 🔹 14. Sorting & Searching

In [21]:
arr = np.array([30, 10, 50, 20])

print(np.sort(arr))
print(np.where(arr == 50))

[10 20 30 50]
(array([2]),)


### 🔹 15. Linear Algebra (Advanced)

In [22]:
A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [5, 6],
    [7, 8]
])

print(np.dot(A, B))
print(np.linalg.det(A))
print(np.linalg.inv(A))

[[19 22]
 [43 50]]
-2.0000000000000004
[[-2.   1. ]
 [ 1.5 -0.5]]


### 🔹 16. Broadcasting

In [23]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

scalar = 10
print(arr + scalar)

[[11 12 13]
 [14 15 16]]


### 🔹 17. Real-World Example: Student Marks Analysis

In [24]:
marks = np.array([
    [85, 90, 88],
    [70, 75, 80],
    [92, 95, 94],
    [60, 65, 58]
])

print(np.mean(marks, axis=1))  # Student-wise average
print(np.mean(marks, axis=0))  # Subject-wise average
print(np.max(marks))           # Top score
print(marks[marks > 80])       # Scores above 80

[87.66666667 75.         93.66666667 61.        ]
[76.75 81.25 80.  ]
95
[85 90 88 92 95 94]


### 🔹 18. Performance: NumPy vs Python List

In [25]:
import time

size = 1_000_000
list_data = list(range(size))
np_data = np.arange(size)

start = time.time()
list_result = [x * 2 for x in list_data]
print("List time:", time.time() - start)

start = time.time()
np_result = np_data * 2
print("NumPy time:", time.time() - start)

List time: 0.054524898529052734
NumPy time: 0.003828287124633789
